services:
  ramen-games:
    build: .
    container_name: ramen-games
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /app
